    language: node_js

    node_js:

        - '20'
    cache:

        directories:

            - node_modules

            - .next/cache [11]

    install:

        - npm install

    script:

        - npm run build
